2023-02-14 17:11:34,785 INFO    MainThread:14040 [internal.py:wandb_internal():89] W&B internal server running at pid: 14040, started at: 2023-02-14 17:11:34.784527
2023-02-14 17:11:34,792 DEBUG   HandlerThread:14040 [handler.py:handle_request():126] handle_request: run_start
2023-02-14 17:11:34,793 INFO    WriterThread:14040 [datastore.py:open_for_write():77] open: /home/bhavyajeet.singh/msme/MEMS-XF2T/generation/mT5-baseline/wandb/offline-run-20230214_171132-2xcaoy9h/run-2xcaoy9h.wandb
2023-02-14 17:11:40,136 DEBUG   HandlerThread:14040 [meta.py:__init__():40] meta init
2023-02-14 17:11:40,137 DEBUG   HandlerThread:14040 [meta.py:__init__():54] meta init done
2023-02-14 17:11:40,137 DEBUG   HandlerThread:14040 [meta.py:probe():211] probe
2023-02-14 17:11:40,146 DEBUG   HandlerThread:14040 [meta.py:_setup_git():201] setup git
2023-02-14 17:11:40,197 DEBUG   HandlerThread:14040 [meta.py:_setup_git():208] setup git done
2023-02-14 17:11:40,197 DEBUG   HandlerThread:14040 [meta.py:_save_pip():58] save pip
2023-02-14 17:11:40,199 DEBUG   HandlerThread:14040 [meta.py:_save_pip():72] save pip done
2023-02-14 17:11:40,199 DEBUG   HandlerThread:14040 [meta.py:_save_conda():79] save conda
2023-02-14 17:12:07,812 DEBUG   HandlerThread:14040 [meta.py:_save_conda():87] save conda done
2023-02-14 17:12:07,812 DEBUG   HandlerThread:14040 [meta.py:probe():249] probe done
2023-02-14 17:16:17,654 WARNING MainThread:14040 [internal.py:wandb_internal():145] Internal process interrupt: 1
2023-02-14 17:16:17,938 WARNING MainThread:14040 [internal.py:wandb_internal():145] Internal process interrupt: 2
2023-02-14 17:16:17,939 ERROR   MainThread:14040 [internal.py:wandb_internal():148] Internal process interrupted.
2023-02-14 17:16:18,686 INFO    WriterThread:14040 [datastore.py:close():281] close: /home/bhavyajeet.singh/msme/MEMS-XF2T/generation/mT5-baseline/wandb/offline-run-20230214_171132-2xcaoy9h/run-2xcaoy9h.wandb
2023-02-14 17:16:18,846 INFO    SenderThread:14040 [sender.py:finish():986] shutting down sender
2023-02-14 17:16:18,847 INFO    MainThread:14040 [internal.py:handle_exit():76] Internal process exited
