01/12/2023 05:42:10 PM [CRITICAL] val: merging the 12 ['as', 'bn', 'en', 'gu', 'hi', 'kn', 'ml', 'mr', 'or', 'pa', 'ta', 'te'] different languages dataset
{'val.jsonl'} files are missing, creating the files..
  | Name  | Type                        | Params
------------------------------------------------------
0 | model | MT5ForConditionalGeneration | 300 M
01/12/2023 05:47:50 PM [CRITICAL] val : script unification to Devanagari is enabled.
01/12/2023 05:47:50 PM [INFO] val dataset count : 239879
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/bhavyajeet.singh/anaconda3/envs/xalign/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/bhavyajeet.singh/anaconda3/envs/xalign/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhavyajeet.singh/anaconda3/envs/xalign/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 215, in check_status
    status_response = self._interface.communicate_stop_status()
  File "/home/bhavyajeet.singh/anaconda3/envs/xalign/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 737, in communicate_stop_status
    resp = self._communicate(req, timeout=timeout, local=True)
  File "/home/bhavyajeet.singh/anaconda3/envs/xalign/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 539, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/bhavyajeet.singh/anaconda3/envs/xalign/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 544, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
