2023-02-04 20:20:38,503 INFO    MainThread:8717 [internal.py:wandb_internal():89] W&B internal server running at pid: 8717, started at: 2023-02-04 20:20:38.502219
2023-02-04 20:20:38,509 DEBUG   HandlerThread:8717 [handler.py:handle_request():126] handle_request: run_start
2023-02-04 20:20:38,511 INFO    WriterThread:8717 [datastore.py:open_for_write():77] open: /home/bhavyajeet.singh/msme/MEMS-XF2T/generation/mT5-baseline/wandb/offline-run-20230204_202036-3m4gmpur/run-3m4gmpur.wandb
2023-02-04 20:20:43,722 DEBUG   HandlerThread:8717 [meta.py:__init__():40] meta init
2023-02-04 20:20:43,722 DEBUG   HandlerThread:8717 [meta.py:__init__():54] meta init done
2023-02-04 20:20:43,722 DEBUG   HandlerThread:8717 [meta.py:probe():211] probe
2023-02-04 20:20:43,732 DEBUG   HandlerThread:8717 [meta.py:_setup_git():201] setup git
2023-02-04 20:20:43,776 DEBUG   HandlerThread:8717 [meta.py:_setup_git():208] setup git done
2023-02-04 20:20:43,776 DEBUG   HandlerThread:8717 [meta.py:_save_pip():58] save pip
2023-02-04 20:20:43,778 DEBUG   HandlerThread:8717 [meta.py:_save_pip():72] save pip done
2023-02-04 20:20:43,779 DEBUG   HandlerThread:8717 [meta.py:_save_conda():79] save conda
2023-02-04 20:20:56,564 DEBUG   HandlerThread:8717 [meta.py:_save_conda():87] save conda done
2023-02-04 20:20:56,565 DEBUG   HandlerThread:8717 [meta.py:probe():249] probe done
2023-02-04 20:22:20,207 WARNING MainThread:8717 [internal.py:wandb_internal():145] Internal process interrupt: 1
2023-02-04 20:22:20,794 WARNING MainThread:8717 [internal.py:wandb_internal():145] Internal process interrupt: 2
2023-02-04 20:22:20,794 ERROR   MainThread:8717 [internal.py:wandb_internal():148] Internal process interrupted.
2023-02-04 20:22:21,538 INFO    SenderThread:8717 [sender.py:finish():986] shutting down sender
2023-02-04 20:22:21,715 INFO    WriterThread:8717 [datastore.py:close():281] close: /home/bhavyajeet.singh/msme/MEMS-XF2T/generation/mT5-baseline/wandb/offline-run-20230204_202036-3m4gmpur/run-3m4gmpur.wandb
2023-02-04 20:22:21,718 INFO    MainThread:8717 [internal.py:handle_exit():76] Internal process exited
