2023-02-14 04:03:20,382 INFO    MainThread:39777 [internal.py:wandb_internal():89] W&B internal server running at pid: 39777, started at: 2023-02-14 04:03:20.380805
2023-02-14 04:03:20,388 INFO    WriterThread:39777 [datastore.py:open_for_write():77] open: /home/bhavyajeet.singh/msme/MEMS-XF2T/generation/mT5-baseline/wandb/offline-run-20230214_040318-8u64luct/run-8u64luct.wandb
2023-02-14 04:03:20,390 DEBUG   HandlerThread:39777 [handler.py:handle_request():126] handle_request: run_start
2023-02-14 04:03:25,050 DEBUG   HandlerThread:39777 [meta.py:__init__():40] meta init
2023-02-14 04:03:25,051 DEBUG   HandlerThread:39777 [meta.py:__init__():54] meta init done
2023-02-14 04:03:25,051 DEBUG   HandlerThread:39777 [meta.py:probe():211] probe
2023-02-14 04:03:25,074 DEBUG   HandlerThread:39777 [meta.py:_setup_git():201] setup git
2023-02-14 04:03:25,128 DEBUG   HandlerThread:39777 [meta.py:_setup_git():208] setup git done
2023-02-14 04:03:25,128 DEBUG   HandlerThread:39777 [meta.py:_save_pip():58] save pip
2023-02-14 04:03:25,130 DEBUG   HandlerThread:39777 [meta.py:_save_pip():72] save pip done
2023-02-14 04:03:25,131 DEBUG   HandlerThread:39777 [meta.py:_save_conda():79] save conda
2023-02-14 04:03:36,608 WARNING MainThread:39777 [internal.py:wandb_internal():145] Internal process interrupt: 1
2023-02-14 04:03:36,776 DEBUG   HandlerThread:39777 [meta.py:_save_conda():87] save conda done
2023-02-14 04:03:36,776 DEBUG   HandlerThread:39777 [meta.py:probe():249] probe done
2023-02-14 04:03:36,815 WARNING MainThread:39777 [internal.py:wandb_internal():145] Internal process interrupt: 2
2023-02-14 04:03:36,815 ERROR   MainThread:39777 [internal.py:wandb_internal():148] Internal process interrupted.
2023-02-14 04:03:37,408 INFO    SenderThread:39777 [sender.py:finish():986] shutting down sender
2023-02-14 04:03:37,786 INFO    WriterThread:39777 [datastore.py:close():281] close: /home/bhavyajeet.singh/msme/MEMS-XF2T/generation/mT5-baseline/wandb/offline-run-20230214_040318-8u64luct/run-8u64luct.wandb
2023-02-14 04:03:37,790 INFO    MainThread:39777 [internal.py:handle_exit():76] Internal process exited
