2023-02-14 04:07:51,990 INFO    MainThread:8287 [internal.py:wandb_internal():89] W&B internal server running at pid: 8287, started at: 2023-02-14 04:07:51.989005
2023-02-14 04:07:51,997 DEBUG   HandlerThread:8287 [handler.py:handle_request():126] handle_request: run_start
2023-02-14 04:07:51,998 INFO    WriterThread:8287 [datastore.py:open_for_write():77] open: /home/bhavyajeet.singh/msme/MEMS-XF2T/generation/mT5-baseline/wandb/offline-run-20230214_040750-2kf5f0rw/run-2kf5f0rw.wandb
2023-02-14 04:07:56,609 DEBUG   HandlerThread:8287 [meta.py:__init__():40] meta init
2023-02-14 04:07:56,610 DEBUG   HandlerThread:8287 [meta.py:__init__():54] meta init done
2023-02-14 04:07:56,610 DEBUG   HandlerThread:8287 [meta.py:probe():211] probe
2023-02-14 04:07:56,619 DEBUG   HandlerThread:8287 [meta.py:_setup_git():201] setup git
2023-02-14 04:07:56,665 DEBUG   HandlerThread:8287 [meta.py:_setup_git():208] setup git done
2023-02-14 04:07:56,665 DEBUG   HandlerThread:8287 [meta.py:_save_pip():58] save pip
2023-02-14 04:07:56,667 DEBUG   HandlerThread:8287 [meta.py:_save_pip():72] save pip done
2023-02-14 04:07:56,667 DEBUG   HandlerThread:8287 [meta.py:_save_conda():79] save conda
2023-02-14 04:08:11,259 DEBUG   HandlerThread:8287 [meta.py:_save_conda():87] save conda done
2023-02-14 04:08:11,260 DEBUG   HandlerThread:8287 [meta.py:probe():249] probe done
2023-02-14 04:08:46,383 WARNING MainThread:8287 [internal.py:wandb_internal():145] Internal process interrupt: 1
2023-02-14 04:08:46,592 WARNING MainThread:8287 [internal.py:wandb_internal():145] Internal process interrupt: 2
2023-02-14 04:08:46,592 ERROR   MainThread:8287 [internal.py:wandb_internal():148] Internal process interrupted.
2023-02-14 04:08:46,906 INFO    WriterThread:8287 [datastore.py:close():281] close: /home/bhavyajeet.singh/msme/MEMS-XF2T/generation/mT5-baseline/wandb/offline-run-20230214_040750-2kf5f0rw/run-2kf5f0rw.wandb
2023-02-14 04:08:47,017 INFO    SenderThread:8287 [sender.py:finish():986] shutting down sender
2023-02-14 04:08:47,018 INFO    MainThread:8287 [internal.py:handle_exit():76] Internal process exited
