2023-02-14 04:10:38,316 INFO    MainThread:25780 [internal.py:wandb_internal():89] W&B internal server running at pid: 25780, started at: 2023-02-14 04:10:38.315020
2023-02-14 04:10:38,323 DEBUG   HandlerThread:25780 [handler.py:handle_request():126] handle_request: run_start
2023-02-14 04:10:38,324 INFO    WriterThread:25780 [datastore.py:open_for_write():77] open: /home/bhavyajeet.singh/msme/MEMS-XF2T/generation/mT5-baseline/wandb/offline-run-20230214_041036-3b66l8fp/run-3b66l8fp.wandb
2023-02-14 04:10:42,911 DEBUG   HandlerThread:25780 [meta.py:__init__():40] meta init
2023-02-14 04:10:42,912 DEBUG   HandlerThread:25780 [meta.py:__init__():54] meta init done
2023-02-14 04:10:42,912 DEBUG   HandlerThread:25780 [meta.py:probe():211] probe
2023-02-14 04:10:42,921 DEBUG   HandlerThread:25780 [meta.py:_setup_git():201] setup git
2023-02-14 04:10:43,034 DEBUG   HandlerThread:25780 [meta.py:_setup_git():208] setup git done
2023-02-14 04:10:43,035 DEBUG   HandlerThread:25780 [meta.py:_save_pip():58] save pip
2023-02-14 04:10:43,037 DEBUG   HandlerThread:25780 [meta.py:_save_pip():72] save pip done
2023-02-14 04:10:43,038 DEBUG   HandlerThread:25780 [meta.py:_save_conda():79] save conda
2023-02-14 04:10:57,617 DEBUG   HandlerThread:25780 [meta.py:_save_conda():87] save conda done
2023-02-14 04:10:57,618 DEBUG   HandlerThread:25780 [meta.py:probe():249] probe done
2023-02-14 04:11:43,410 WARNING MainThread:25780 [internal.py:wandb_internal():145] Internal process interrupt: 1
2023-02-14 04:11:43,753 WARNING MainThread:25780 [internal.py:wandb_internal():145] Internal process interrupt: 2
2023-02-14 04:11:43,754 ERROR   MainThread:25780 [internal.py:wandb_internal():148] Internal process interrupted.
2023-02-14 04:11:44,349 INFO    SenderThread:25780 [sender.py:finish():986] shutting down sender
2023-02-14 04:11:44,514 INFO    WriterThread:25780 [datastore.py:close():281] close: /home/bhavyajeet.singh/msme/MEMS-XF2T/generation/mT5-baseline/wandb/offline-run-20230214_041036-3b66l8fp/run-3b66l8fp.wandb
2023-02-14 04:11:44,518 INFO    MainThread:25780 [internal.py:handle_exit():76] Internal process exited
