2023-02-08 02:48:41,462 INFO    MainThread:6785 [internal.py:wandb_internal():89] W&B internal server running at pid: 6785, started at: 2023-02-08 02:48:41.460862
2023-02-08 02:48:41,468 DEBUG   HandlerThread:6785 [handler.py:handle_request():126] handle_request: run_start
2023-02-08 02:48:41,470 INFO    WriterThread:6785 [datastore.py:open_for_write():77] open: /home/bhavyajeet.singh/msme/MEMS-XF2T/generation/mT5-baseline/wandb/offline-run-20230208_024839-38rrb6ut/run-38rrb6ut.wandb
2023-02-08 02:48:46,087 DEBUG   HandlerThread:6785 [meta.py:__init__():40] meta init
2023-02-08 02:48:46,087 DEBUG   HandlerThread:6785 [meta.py:__init__():54] meta init done
2023-02-08 02:48:46,087 DEBUG   HandlerThread:6785 [meta.py:probe():211] probe
2023-02-08 02:48:46,098 DEBUG   HandlerThread:6785 [meta.py:_setup_git():201] setup git
2023-02-08 02:48:46,144 DEBUG   HandlerThread:6785 [meta.py:_setup_git():208] setup git done
2023-02-08 02:48:46,144 DEBUG   HandlerThread:6785 [meta.py:_save_pip():58] save pip
2023-02-08 02:48:46,146 DEBUG   HandlerThread:6785 [meta.py:_save_pip():72] save pip done
2023-02-08 02:48:46,146 DEBUG   HandlerThread:6785 [meta.py:_save_conda():79] save conda
2023-02-08 02:49:06,549 DEBUG   HandlerThread:6785 [meta.py:_save_conda():87] save conda done
2023-02-08 02:49:06,549 DEBUG   HandlerThread:6785 [meta.py:probe():249] probe done
2023-02-08 02:49:15,325 WARNING MainThread:6785 [internal.py:wandb_internal():145] Internal process interrupt: 1
2023-02-08 02:49:15,853 WARNING MainThread:6785 [internal.py:wandb_internal():145] Internal process interrupt: 2
2023-02-08 02:49:15,854 ERROR   MainThread:6785 [internal.py:wandb_internal():148] Internal process interrupted.
2023-02-08 02:49:16,138 INFO    WriterThread:6785 [datastore.py:close():281] close: /home/bhavyajeet.singh/msme/MEMS-XF2T/generation/mT5-baseline/wandb/offline-run-20230208_024839-38rrb6ut/run-38rrb6ut.wandb
2023-02-08 02:49:16,502 INFO    SenderThread:6785 [sender.py:finish():986] shutting down sender
2023-02-08 02:49:16,503 INFO    MainThread:6785 [internal.py:handle_exit():76] Internal process exited
