2023-02-08 03:13:36,061 INFO    MainThread:11055 [internal.py:wandb_internal():89] W&B internal server running at pid: 11055, started at: 2023-02-08 03:13:36.060168
2023-02-08 03:13:36,068 DEBUG   HandlerThread:11055 [handler.py:handle_request():126] handle_request: run_start
2023-02-08 03:13:36,069 INFO    WriterThread:11055 [datastore.py:open_for_write():77] open: /home/bhavyajeet.singh/msme/MEMS-XF2T/generation/mT5-baseline/wandb/offline-run-20230208_031334-8c6sphoz/run-8c6sphoz.wandb
2023-02-08 03:13:40,642 DEBUG   HandlerThread:11055 [meta.py:__init__():40] meta init
2023-02-08 03:13:40,643 DEBUG   HandlerThread:11055 [meta.py:__init__():54] meta init done
2023-02-08 03:13:40,643 DEBUG   HandlerThread:11055 [meta.py:probe():211] probe
2023-02-08 03:13:40,652 DEBUG   HandlerThread:11055 [meta.py:_setup_git():201] setup git
2023-02-08 03:13:40,696 DEBUG   HandlerThread:11055 [meta.py:_setup_git():208] setup git done
2023-02-08 03:13:40,696 DEBUG   HandlerThread:11055 [meta.py:_save_pip():58] save pip
2023-02-08 03:13:40,698 DEBUG   HandlerThread:11055 [meta.py:_save_pip():72] save pip done
2023-02-08 03:13:40,709 DEBUG   HandlerThread:11055 [meta.py:_save_conda():79] save conda
2023-02-08 03:13:44,432 WARNING MainThread:11055 [internal.py:wandb_internal():145] Internal process interrupt: 1
2023-02-08 03:13:44,548 DEBUG   HandlerThread:11055 [meta.py:_save_conda():87] save conda done
2023-02-08 03:13:44,548 DEBUG   HandlerThread:11055 [meta.py:probe():249] probe done
2023-02-08 03:13:44,793 WARNING MainThread:11055 [internal.py:wandb_internal():145] Internal process interrupt: 2
2023-02-08 03:13:44,793 ERROR   MainThread:11055 [internal.py:wandb_internal():148] Internal process interrupted.
2023-02-08 03:13:45,082 INFO    SenderThread:11055 [sender.py:finish():986] shutting down sender
2023-02-08 03:13:45,569 INFO    WriterThread:11055 [datastore.py:close():281] close: /home/bhavyajeet.singh/msme/MEMS-XF2T/generation/mT5-baseline/wandb/offline-run-20230208_031334-8c6sphoz/run-8c6sphoz.wandb
2023-02-08 03:13:45,572 INFO    MainThread:11055 [internal.py:handle_exit():76] Internal process exited
